"""Initial

Revision ID: dc0de2e637d3
Revises: 
Create Date: 2022-10-03 13:31:27.243396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0de2e637d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='yatube'
    )
    op.create_index(op.f('ix_yatube_users_id'), 'users', ['id'], unique=False, schema='yatube')
    op.create_index(op.f('ix_yatube_users_username'), 'users', ['username'], unique=True, schema='yatube')
    op.create_table('posts',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['yatube.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='yatube'
    )
    op.create_index(op.f('ix_yatube_posts_id'), 'posts', ['id'], unique=False, schema='yatube')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yatube_posts_id'), table_name='posts', schema='yatube')
    op.drop_table('posts', schema='yatube')
    op.drop_index(op.f('ix_yatube_users_username'), table_name='users', schema='yatube')
    op.drop_index(op.f('ix_yatube_users_id'), table_name='users', schema='yatube')
    op.drop_table('users', schema='yatube')
    # ### end Alembic commands ###
